package com.secure.secureAPP.user;

public enum Permission {
//    MANAGE_USERS, FULL_ACCESS, MANAGE_ACCOUNTS,
//    APPROVE_TRANSACTIONS, VIEW_ALL_ACCOUNTS,
//    MANAGE_OWN_ACCOUNT, VIEW_OWN_ACCOUNT,

    // SECURE APP DEMO PERMISSIONS
    ADMIN_READ,
    ADMIN_CREATE,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    EMPLOYEE_READ,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE
}
